name: enarxbot

on:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  pull_request_target:
  push:
  registry_package:
  release:
  status:
  watch:
  workflow_run:
    workflows: ["enarxbot"]
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  enarxbot:
    runs-on: ubuntu-latest
    name: enarxbot
    steps:
      - uses: enarx/bot@master
