name: enarxbot

on:
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request_target:
  push:
  registry_package:
  release:
  status:
  watch:
  workflow_run:
    workflows: [enarxbot-prr]
    types: [completed]
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  enarxbot:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    name: enarxbot
    steps:
      - uses: enarx/bot@dev
